### ISSUE TITLE
Beginning of Variables Editable

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#346] opened 2020-03-13 13:48 UTC
**Describe the bug**
If the user moves to the left side of the first `"` in a variable, they can edit outside the `"..."` of the variable

**To Reproduce**
1. Go to [the demo](https://cicero-ui.netlify.com/)
2. Click anywhere in `...shall pay to...` in the first line
3. Right arrow to the left side of the first `"` in `"Steve"`
4. Type anything, see nothing is allowed.
5. Right arrow into `"Steve"`, then left arrow back to the left side of the first `"` in `"Steve"`
6. Type anything, see that it **IS** allowed

**Expected behavior**
This should be restricted because it should be outside the variable

**Comment by DianaLease** [comment] 2020-03-13 13:57
I think the main issue with this is more about the user knowing the variable needs to start with a quote. When I do the steps listed in the issue to reproduce, I'm still inside the variable (any new text I type is blue and can still be removed). The issue is it won't parse unless I add a new quotation at the start of the variable.

I'm not sure how to make that apparent to the user. Maybe we can think about not letting the user remove the quotes? I know this issue with quotes might change in the future as well since many users have said they do not want to see the quotes rendered at all.

**Comment by irmerk** [comment] 2020-03-13 13:59
Excellent point. And this goes back into the ongoing discussion we have for variables being edited through a pop-up editor, which would make this issue moot.

**Comment by jerrybuks** [comment] 2020-03-13 18:38
I think I can help with this, the reason while this happens is that the anchor.offset value changes. when you Right arrow to the left side of the first " in "Steve", the current implementation sees it that you are not in the variable yet (anchor.offset is 27) and therefore prevents editing, but once you Right arrow into "Steve", then left arrow back to the left side of the first " in "Steve", it then now sees this position as inside the variable (anchor.offset is 0), therefore it allows editing.

**Comment by jerrybuks** [comment] 2020-03-13 21:35
> I think the main issue with this is more about the user knowing the variable needs to start with a quote. When I do the steps listed in the issue to reproduce, I'm still inside the variable (any new text I type is blue and can still be removed). The issue is it won't parse unless I add a new quotation at the start of the variable.
> 
> I'm not sure how to make that apparent to the user. Maybe we can think about not letting the user remove the quotes? I know this issue with quotes might change in the future as well since many users have said they do not want to see the quotes rendered at all.

I think not letting the user remove the quotes, and ensuring that editing only happens in between the quotes will solve this issue

**Comment by algomaster99** [comment] 2020-03-17 12:12
@DianaLease @irmerk To begin with getting familiar with Accord Project, I would like to take this issue up. Before that, I had one doubt. Should I just try to prevent a user from removing the `"`. If yes, can you let me know where the logic for preventing edits in the template is written?

**Comment by dselman** [comment] 2020-03-17 12:15
Let's hold off on this until the migration to Slate 0.50 is complete.
https://github.com/accordproject/markdown-editor/issues/297

**Comment by irmerk** [comment] 2020-04-10 20:47
@algomaster99 @jerrybuks:

#357 (and accordproject/markdown-editor#297) has been finished, so there is no longer a blocker on this issue. The migration _may_ have solved this issue, so look into that first.

**Comment by jerrybuks** [comment] 2020-04-10 20:53
> @algomaster99 @jerrybuks:
> 
> #357 (and [accordproject/markdown-editor#297](https://github.com/accordproject/markdown-editor/issues/297)) has been finished, so there is no longer a blocker on this issue. The migration _may_ have solved this issue, so look into that first.

Awesome, will get back at it

**Comment by jerrybuks** [comment] 2020-04-11 12:09
@irmerk, one can still edit text at the beginning of variables (i.e before the opening quotation mark), but it seems not to be an issue again, as the variables are now in a container with a different background, so it's quite obvious to the user that they are still in a variable and should, therefore, adjust the starting quotation mark. please kindly take a look and suggest if the editing before the first ", should still be restricted.

**Comment by irmerk** [comment] 2020-04-12 19:51
I think the current status is what we want. @Michael-Grover @DianaLease thoughts?

**Comment by DianaLease** [comment] 2020-04-13 13:05
@irmerk Yes, with the new slate migration, I believe we can close this issue.

**Closed** 2020-04-13 13:29 UTC
Labels: Difficulty: Medium, Good First Issue :octocat:, Type: Bug 🐛
